;;;; interface.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'interface
      'interface
      (scheme#list)
      '((key-right-pressed? . interface#key-right-pressed?)
        (key-left-pressed? . interface#key-left-pressed?)
        (key-down-pressed? . interface#key-down-pressed?)
        (key-up-pressed? . interface#key-up-pressed?)
        (should-close-app-window? . interface#should-close-app-window?)
        (create-app-window . interface#create-app-window))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
