;;;; interface.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'interface
      'interface
      (scheme#list)
      '((should-close-app-window? . interface#should-close-app-window?)
        (create-app-window . interface#create-app-window)
        (set-backend . interface#set-backend)
        (rendering-backend . interface#rendering-backend))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
