;;;; minifb-backend.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'minifb-backend
      'minifb-backend
      (scheme#list)
      '((mfbb-create-window . minifb-backend#mfbb-create-window)
        (mfbb-is-app-closed? . minifb-backend#mfbb-is-app-closed?))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
