;;;; renderer-logic.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'renderer-logic
      'renderer
      (scheme#list)
      '((load-image . renderer-logic#load-image)
        (reset-fb . renderer-logic#reset-fb)
        (draw-rectangle . renderer-logic#draw-rectangle)
        (draw-image . renderer-logic#draw-image)
        (init-fb . renderer-logic#init-fb)
        (rgb-length . renderer-logic#rgb-length)
        (rgba-length . renderer-logic#rgba-length)
        (sync-fb-to-x11-memory . renderer-logic#sync-fb-to-x11-memory)
        (return-fb . renderer-logic#return-fb)
        (return-fb-locative . renderer-logic#return-fb-locative)
        (upscale-fb . renderer-logic#upscale-fb))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
