;;;; renderer-logic.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'renderer-logic
      'renderer-logic
      (scheme#list)
      '((load-image . renderer-logic#load-image)
        (reset-fb . renderer-logic#reset-fb)
        (draw-rectangle . renderer-logic#draw-rectangle)
        (draw-image . renderer-logic#draw-image)
        (fb-length . renderer-logic#fb-length)
        (rgb-length . renderer-logic#rgb-length)
        (rgba-length . renderer-logic#rgba-length)
        (return-fb . renderer-logic#return-fb))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
