;;;; sdl2-backend.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'sdl2-backend
      'sdl2-backend
      (scheme#list)
      '((init-backend . sdl2-backend#init-backend)
        (render-frame . sdl2-backend#render-frame))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
