;;;; x11-backend.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'x11-backend
      'x11-backend
      (scheme#list)
      '((is-app-closed? . x11-backend#is-app-closed?)
        (xlib-key-right-pressed? . x11-backend#xlib-key-right-pressed?)
        (xlib-key-left-pressed? . x11-backend#xlib-key-left-pressed?)
        (xlib-key-down-pressed? . x11-backend#xlib-key-down-pressed?)
        (xlib-key-up-pressed? . x11-backend#xlib-key-up-pressed?)
        (create-window . x11-backend#create-window)
        (close-app . x11-backend#close-app)
        (is-mapped . x11-backend#is-mapped)
        (keyboard-state . x11-backend#keyboard-state)
        (xlib-display . x11-backend#xlib-display)
        (should-close . x11-backend#should-close))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
